### ISSUE TITLE
console.log is weird

### ISSUE THREAD

**Issue by t7yang** [nathanchapman/vscode-javascript-snippets#1]
simply `console.log(${0})${1}` is enough.

**Comment by nathanchapman** [comment]
@t7yang thanks for the suggestion. I frequently use this format because it adds a label.
It allows me to do `console.log('someVariable', someVariable)` to see what I'm logging at the same time as the data it contains. But you're right, the default behavior should be a normal `console.log`

I updated the package a couple of days ago (before seeing this issue). It should be fixed now and `cl⇥` should be your standard console.log, while I moved that other functionality over to `cll⇥` for `console.log labeled`

Please let me know if there's anything else weird. This is still a brand new package and my first extension for VS Code. I was previously a die-hard Atom user, but moved over for the debugging tools.

**Comment by kimsovan72** [comment]
[Microsoft/vscode] Could you make IntelliSense working independently from the order of the "multi cursoring"? (#59086) 
Username: kimsovan72 
FirstName: Kim 
LastName: Sovan 
Email: kimsovan72@gmail.com
